<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="ExternalServices\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MHPlatform.Application\MHPlatform.Application.csproj" />
    <ProjectReference Include="..\MHPlatform.Domain\MHPlatform.Domain.csproj" />
  </ItemGroup>

</Project>
